// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qx7dDf2KLsnq7k2Leb7m5UHUcyK6fzM',
    appId: '1:575923621555:web:d100221dc3fac40d92aac6',
    messagingSenderId: '575923621555',
    projectId: 'movieapp-3fcd5',
    authDomain: 'movieapp-3fcd5.firebaseapp.com',
    storageBucket: 'movieapp-3fcd5.firebasestorage.app',
    measurementId: 'G-4HB068XEP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKdiLTndX9M8F6D9kXd4qKo1PrRmJ33w',
    appId: '1:575923621555:android:2af3f2332552ba1592aac6',
    messagingSenderId: '575923621555',
    projectId: 'movieapp-3fcd5',
    storageBucket: 'movieapp-3fcd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz112nv0EZyTNBqOO3jUV1WZaBsQCOpU',
    appId: '1:575923621555:ios:7aa2fd24b488694192aac6',
    messagingSenderId: '575923621555',
    projectId: 'movieapp-3fcd5',
    storageBucket: 'movieapp-3fcd5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfz112nv0EZyTNBqOO3jUV1WZaBsQCOpU',
    appId: '1:575923621555:ios:7aa2fd24b488694192aac6',
    messagingSenderId: '575923621555',
    projectId: 'movieapp-3fcd5',
    storageBucket: 'movieapp-3fcd5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4qx7dDf2KLsnq7k2Leb7m5UHUcyK6fzM',
    appId: '1:575923621555:web:67efef91c1760cb092aac6',
    messagingSenderId: '575923621555',
    projectId: 'movieapp-3fcd5',
    authDomain: 'movieapp-3fcd5.firebaseapp.com',
    storageBucket: 'movieapp-3fcd5.firebasestorage.app',
    measurementId: 'G-CQ4C4WFS9J',
  );
}
